AllCops:
  RunRailsCops: true
  Exclude:
    - "*.gemspec"
    - "bin/*"
    - "config/initializers/devise.rb"
    - "db/schema.rb"

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15

Style/Documentation:
  Enabled: false
